<style>
    table, th, td {
        border-collapse: collapse;
    }

    td {
        height: 30px;
        vertical-align: bottom;
    }

    th, td {
        padding: 5px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    .head {
        background-color: #3c84b4;
    }


    tr:nth-child(even) {
        background-color: #f2f2f2;}
</style>
<html>
    <span>Dear <?= $employeename ?>
    <p>Please use information 
            below to access our printers</p>
    <br>
    <table>
        <tr class="head">
            <td>A</td>
            <td colspan="3">
                <strong>
                    Sharp Printer Details
                </strong>
            </td>
        </tr>
        <tr>
            <td>1</td>
            <td>ID Employee</td>

            <td>:</td>
            <td><?= $idemployee; ?></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Name</td>
            <td>:</td>
            <td><?= $employeename; ?></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Department</td>
            <td>:</td>
            <td><?= $deptdesc; ?></td>
        </tr>
        <tr>
            <td>4</td>
            <td>Position</td>
            <td>:</td>
            <td><?= $positiondesc; ?></td>
        </tr>
        <tr>
            <td>5</td>
            <td>Email Address</td>
            <td>:</td>
            <td><?= $recipient; ?></td>
        </tr>
        <tr class="head">
            <td>C</td>
            <td colspan="3"><strong>Printer Access</strong></td>
        </tr>
        <tr>
            <td>1</td>
            <td>Printer ID</td>

            <td>:</td>
            <td><?= $idemployee; ?></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Printer</td>
            <td></td>
            <td>Password</td>
        </tr>
        <tr>
            <td></td>
            <td>Other Printer</td>
            <td>:</td>
            <td><?= $others_password; ?></td>
        </tr>
        <tr>
            <td></td>
            <td>Sharp Printer</td>
            <td>:</td>
            <td><?= $sharp_password; ?></td>
        </tr>
    </table>
    <p>
        Note: This email is generated by system.
        for further communication please contact email below: <br>
        Mustafa : mustafa.m@wascoenergy.com <br> 
        Wahyu Maulana : wahyu.waulana@wascoenergy.com <br> 
        Ichwan Maulana : ichwan.maulana@wascoenergy.com     
    </p>
</html>